version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      - TZ=Asia/Tokyo

  db:
    image: postgres
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: "Asia/Tokyo"
      PGTZ: "Asia/Tokyo"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
